CHANGELOG.md
=> release for v0.0.2

CHANGELOG.md
=> release for v0.0.3

go.mod, go.sum, vendor/github.com/vultr/metadata/CHANGELOG.md, vendor/github.com/vultr/metadata/go.mod, vendor/github.com/vultr/metadata/metadata_json.go, vendor/modules.txt
update metadata client to support new changes
=> update metadata client for new changes

docs/releases/latest.yml, docs/releases/nightly.yml, docs/releases/v0.1.0.yml, docs/releases/v0.1.1.yml
Adding default fstype for the csi-provisioner
=> defaulting fstype

Makefile
=> Add -trimpath to builds

cmd/csi-vultr-driver/main.go, driver/driver.go
Add ability to modify user agent
=> Ability to modify user agent

docs/releases/nightly.yml
Changed CSIDriver apiVersion to v1
Bumped csi-provisioner to v3.1.0
Bumped csi-attacher to v3.4.0
Bumped csi-node-driver-registrar to v2.5.0
=> Updated nightly dependencies

docs/kubernetes/README.md
=> Fix typo in documentation

LICENSE
Add the ALv2 license file to the repository.
=> Add ALv2 license

.goreleaser.yml, docs/releases/v0.8.0.yml
=> Release v0.8.0 #minor

Dockerfile, driver/controller.go, driver/driver_test.go, driver/mounter.go, driver/node.go
This PR will add PVC stats RPC call to CSI. 
CLOUD-2701
=> added volume stats rpc

docs/releases/latest.yml, docs/releases/nightly.yml, driver/controller.go, driver/identity.go, driver/node.go
This PR will add volume expansion capabilities to the CSI
=> added volume expansion

go.mod, go.sum, vendor/github.com/vultr/govultr/v3/CHANGELOG.md, vendor/github.com/vultr/govultr/v3/README.md, vendor/github.com/vultr/govultr/v3/bare_metal_server.go, vendor/github.com/vultr/govultr/v3/container_registry.go, vendor/github.com/vultr/govultr/v3/database.go, vendor/github.com/vultr/govultr/v3/govultr.go, vendor/github.com/vultr/govultr/v3/instance.go, vendor/github.com/vultr/govultr/v3/marketplace.go, vendor/modules.txt
Update govultr and redo release pipeline run
=> Release v0.12.0 #minor

driver/controller.go, driver/node.go
This PR will set node expansion required to `true` which will ensure node expansion RPC is called.
=> Resolve CSI expansion issues

.golangci.yaml, driver/driver.go, driver/mounter.go, driver/node.go, driver/server.go
* Exclude the gosec warning https://github.com/securego/gosec/issues/106
* Add some doc strings
* Remove unnecessary conversions
=> Fix some lint issues and update the linter configuration

driver/node.go
Add int64 conversion back & ignore linting error
=> Fix ARM builds with type conversion 

.github/workflows/notify-issue.yml, .github/workflows/notify-pr.yml, .github/workflows/releaser.yml
Fix broken action after major version update
=> Update mattermost notify action

CHANGELOG.md, docs/releases/latest.yml, docs/releases/nightly.yml, docs/releases/v0.12.4.yml
Release v0.12.4 #patch
#212 
#203 
#209
=> Release v0.12.4 #patch

.github/workflows/releaser.yml
* Fixes the notification when goreleaser is finished
=> Fix releaser mattermost notification action

go.mod, go.sum, vendor/github.com/vultr/govultr/v3/CHANGELOG.md, vendor/github.com/vultr/govultr/v3/database.go, vendor/github.com/vultr/govultr/v3/govultr.go, vendor/modules.txt
=> Update govultr from v3.11.1 to v3.11.2

docs/kubernetes/README.md
Simply fix the link path cuz the current link is pointing to the 404.
=> Fix broken link in README.md

.github/workflows/notify-pr.yml, .github/workflows/releaser.yml, .goreleaser.yml
This PR will update the deploy action file to upload csi images to VCR as well as DH. Additionally, it includes a fix for the MM integration.
#266
=> add builds to public vcr repo

go.mod, go.sum, vendor/github.com/vultr/govultr/v3/CHANGELOG.md, vendor/github.com/vultr/govultr/v3/database.go, vendor/github.com/vultr/govultr/v3/govultr.go, vendor/github.com/vultr/govultr/v3/virtual_file_system_storage.go, vendor/modules.txt
Update govultr from v3.11.2 to v3.13.0
=> Update govultr from v3.11.2 to v3.13.0

.github/workflows/coverage.yml, .github/workflows/go-checks.yml, .github/workflows/main.yml, .github/workflows/releaser.yml, .github/workflows/unit-tests.yml, go.mod
=> Update Go version from v1.23 to v1.24

go.mod, go.sum, vendor/github.com/vultr/govultr/v3/CHANGELOG.md, vendor/github.com/vultr/govultr/v3/bare_metal_server.go, vendor/github.com/vultr/govultr/v3/govultr.go, vendor/github.com/vultr/govultr/v3/kubernetes.go, vendor/modules.txt
Update govultr from v3.16.1 to v3.18.0
=> Update govultr from v3.16.1 to v3.18.0

.github/workflows/releaser.yml
=> Update github-tag-actions from v1.36.0 to v1.71.0

CHANGELOG.md, docs/releases/latest.yml, docs/releases/nightly.yml
Release v0.17.0 #minor
#328 
#321 
#320 
#327 
#326 
#323 
#322 
#330 
#329 
#333 
#332 
#331
=> Release v0.17.0 #minor
